version: "3.8"
services:
  redis:
    image: redis
    command: redis-server --requirepass "redis-password"
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - PORT=3001
      - REDISHOST=redis
      - REDISPORT=6379
      - REDISPASSWORD=redis-password
    volumes:
      - ./:/srv/contadordevoleybe/
    ports:
      - "3001:3001"
    depends_on:
      - redis
